sudo: required
services:
  - docker
before_install:
  - docker build -t acaporrini/fibonacci_calculator_client_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true acaporrini/fibonacci_calculator_client_test npm test -- --coverage

after_success:
  # Build production images
  - docker build -t acaporrini/fibonacci_calculator_client ./client
  - docker build -t acaporrini/fibonacci_calculator_server ./server
  - docker build -t acaporrini/fibonacci_calculator_nginx ./nginx
  - docker build -t acaporrini/fibonacci_calculator_worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push acaporrini/fibonacci_calculator_client
  - docker push acaporrini/fibonacci_calculator_server
  - docker push acaporrini/fibonacci_calculator_nginx
  - docker push acaporrini/fibonacci_calculator_worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'fibonacci_calculator'
  env: 'Fibonaccicalculator-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-363584523866'
  bucket_path: 'fibonacci_calculator'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
